# Application settings

# All files generated by this program will be stored and read from here
APPLICATION_DATA_PATH = './tmp'

# Stores information about currently in use model
MODEL_INFO_DATA_FILE = 'model.json'