version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - chatbot-data:/var/lib/postgresql/data

volumes:
  chatbot-data: