"""chat model build_log added

Revision ID: 36fe12893597
Revises: de3c73c83e6b
Create Date: 2023-11-15 09:41:53.340296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36fe12893597'
down_revision: Union[str, None] = 'de3c73c83e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_model', sa.Column('build_log', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_model', 'build_log')
    # ### end Alembic commands ###
