"""using ARRAY

Revision ID: b7d6717fd953
Revises: faa1679b5ef5
Create Date: 2023-11-15 07:59:41.999996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7d6717fd953'
down_revision: Union[str, None] = 'faa1679b5ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_response_id', table_name='response')
    op.drop_table('response')
    op.drop_index('ix_pattern_id', table_name='pattern')
    op.drop_table('pattern')
    op.add_column('intent', sa.Column('patterns', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('intent', sa.Column('responses', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intent', 'responses')
    op.drop_column('intent', 'patterns')
    op.create_table('pattern',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pattern', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('intent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['intent_id'], ['intent.id'], name='pattern_intent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pattern_pkey')
    )
    op.create_index('ix_pattern_id', 'pattern', ['id'], unique=False)
    op.create_table('response',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('response', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('intent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['intent_id'], ['intent.id'], name='response_intent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='response_pkey')
    )
    op.create_index('ix_response_id', 'response', ['id'], unique=False)
    # ### end Alembic commands ###
