"""unique profile uid

Revision ID: de3c73c83e6b
Revises: b7d6717fd953
Create Date: 2023-11-15 09:13:10.575173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de3c73c83e6b'
down_revision: Union[str, None] = 'b7d6717fd953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_profile_uid', table_name='profile')
    op.create_index(op.f('ix_profile_uid'), 'profile', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_uid'), table_name='profile')
    op.create_index('ix_profile_uid', 'profile', ['uid'], unique=False)
    # ### end Alembic commands ###
