"""init

Revision ID: faa1679b5ef5
Revises: 14de16643817
Create Date: 2023-11-15 06:02:16.344908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa1679b5ef5'
down_revision: Union[str, None] = '14de16643817'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('state', sa.Enum('INIT', 'TRAINED', 'TRAINING', 'ERROR', name='chatmodelstatus'), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intent_tag'), 'intent', ['tag'], unique=False)
    op.create_table('profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_uid'), 'profile', ['uid'], unique=False)
    op.create_table('message_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('state', sa.Enum('REPLIED', 'INTENT_NOT_FOUND', 'BELOW_THRESHOLD', name='messagestate'), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('intent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['intent_id'], ['intent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_log_uid'), 'message_log', ['uid'], unique=False)
    op.create_table('pattern',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pattern', sa.String(), nullable=True),
    sa.Column('intent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['intent_id'], ['intent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pattern_id'), 'pattern', ['id'], unique=False)
    op.create_table('response',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('intent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['intent_id'], ['intent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_id'), 'response', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_response_id'), table_name='response')
    op.drop_table('response')
    op.drop_index(op.f('ix_pattern_id'), table_name='pattern')
    op.drop_table('pattern')
    op.drop_index(op.f('ix_message_log_uid'), table_name='message_log')
    op.drop_table('message_log')
    op.drop_index(op.f('ix_profile_uid'), table_name='profile')
    op.drop_table('profile')
    op.drop_index(op.f('ix_intent_tag'), table_name='intent')
    op.drop_table('intent')
    op.drop_table('chat_model')
    # ### end Alembic commands ###
