# Application settings

# All files generated by this program will be stored and read from here
APPLICATION_DATA_PATH = "./tmp"

# Database connection url
SQLALCHEMY_DATABASE_URI = "postgresql://postgres:password@localhost/postgres"
